const projectData = [
  {
    title: "Pokemons App",
    id: "7",
    link: "https://alekseevaiana.github.io/pokemons",
    github_link: "https://github.com/alekseevaiana/pokemons",
    description: "React application with using external API.",
    teck: "Figma, React, JavaScript, CSS, HTML",
    teck_array: ["Figma", "React", "JavaScript", "CSS", "HTML"],
  },
  {
    title: "My_Basecamp",
    id: "1",
    image: "img/basecamp.png",
    link: "https://basecamp-17.herokuapp.com",
    github_link: "https://github.com/alekseevaiana/my_basecamp",
    description: "This project is developing in Ruby on Rails.",
    teck: "Ruby, Ruby on Rails, SQL, SASS, CSS, HTML",
    teck_array: ["Ruby", "Ruby on Rails", "SQL", "CSS", "HTML"],
  },
  {
    title: "Vinishko",
    id: "2",
    image: "./img/vinishko.png",
    link: "https://alekseevaiana.github.io/vinishko/",
    github_link: "https://github.com/alekseevaiana/vinishko",
    description: "My first application built using React Framework",
    teck: "React, JavaScript, CSS, HTML",
    teck_array: ["React", "JavaScript", "CSS", "HTML"],
  },
  {
    title: "Pink",
    id: "3",
    image: "./img/pink.jpg",
    link: "https://alekseevaiana.github.io/pink/",
    github_link: "https://github.com/alekseevaiana/505469-pink",
    description: "Project converted from PSD into a HTML-CSS layout.",
    teck: "CSS, HTML, SVG, LESS, GULP, Cross-Browser Compatibility, Responsive and Adaptive templates",
    teck_array: [
      "CSS",
      "HTML",
      "SVG",
      "LESS",
      "GULP",
      "Cross-Browser Compatibility",
      "Responsive and Adaptive templates",
    ],
  },

  // {
  //   title: "Sedona",
  //   id: "5",
  //   image: "./img/sedona.jpg",
  //   link: "https://alekseevaiana.github.io/sedona/",
  //   github_link: "https://github.com/alekseevaiana/505469-sedona",
  //   description: "Project converted from PSD into a HTML-CSS layout.",
  //   teck: "CSS, HTML, Cross-Browser Compatibility",
  //   teck_array: ["CSS", "HTML", "Cross-Browser Compatibility"],
  // },
  {
    title: "Interior Design",
    id: "6",
    image: "./img/interior-design-for-portfolio.jpg",
    link: "https://alekseevaiana.github.io/interior_design/",
    github_link: "https://github.com/alekseevaiana/interior_design",
    description: "Project converted from PSD into a HTML-CSS layout.",
    teck: "CSS, HTML, Cross-Browser Compatibility",
    teck_array: ["CSS", "HTML", "Cross-Browser Compatibility"],
  },
  {
    title: "My_tar",
    id: "4",
    image: null,
    link: null,
    github_link: "https://github.com/alekseevaiana/my_tar",
    description:
      "One of my favorite projects written in C language. It is a Linux/Unix implementation of tar command.",
    teck: "C, CLI",
    teck_array: ["C", "CLI"],
  },
];

export default projectData;
